# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.

os: linux

before_install:
  - npm install remark-cli remark-validate-links

script:
  - echo "helloworld"

import:
  - credentials.yml
  - .travis-merger.yml
  - .travis-stages.yml
